apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: asset-storage
  labels:
    app: specify
    component: asset-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
